### ISSUE TITLE
Transfer to the community?

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/sensu-plugins-azurerm#13]
Hello Tom,

I am a maintainer for https://github.com/sensu-plugins and found this repo, wondering if you might be interested in transferring it over to the community. I discovered this while facilitating https://github.com/sensu-plugins/community/issues/72 If you are interested please reply back to either repo and I can start the process transfer which is outlined [here](https://github.com/sensu-plugins/community/blob/master/TRANSFERRING_REPOS.md)

**Comment by tombuildsstuff** [comment]
@majormoses sure, that sounds good 👍

**Comment by majormoses** [comment]
If you can transfer the repo to me I will transfer it to the org. Also could you please run `gem owner sensu-plugins-azurerm -a sensu-plugin@sensu-plugins.io` to give us permission to push to rubygems from travis?

**Comment by tombuildsstuff** [comment]
@majormoses sure - I'll kick this off this weekend.

**Comment by tombuildsstuff** [comment]
@majormoses I've added Gem permissions for the `sensu-plugin@sensu-plugins.io` user (via the command above).

Just waiting to hear back before transferring the repo - which should be later today :)

**Comment by tombuildsstuff** [comment]
@majormoses just to let you know that I've heard back (just wanted to confirm a old user wasn't `gem installing` directly 😄)

I'll kick this off now.. :)

**Comment by majormoses** [comment]
I have transferred over the repo and confirmed that I see our user has access to it on rubygems.org. I am gonna close this out at this point. Just to give you an idea of what else I will do in the next week or so:
- bring in standard stuff from our skel (PR templates, Rakefiles, gemspecs, rubocop, etc)
- import this into our terraform and ensure that it has our standard community labels.
- make travis ci setup and deploy from the our user
- create a skel for setting up integration tests with `test-kitchen`, `kitchen-docker`, and `serverspec`
- update any badges or links
